apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  strategy: {}
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: amazon/aws-cli
        command:
          - sh
          - -c
          - |
            echo "Listing buckets..."
            aws s3 ls
            sleep 3600
        name: aws-list-buckets
        resources: {}
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: secrets-demo
                key: aws-access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: secrets-demo
                key: aws-secret-access-key
          - name: AWS_SESSION_TOKEN
            valueFrom:
              secretKeyRef:
                name: secrets-demo
                key: aws-session-token
status: {}
