apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secrets-demo
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: my-secret-store
    kind: SecretStore
  target:
    name: secrets-demo
    creationPolicy: Owner
  data:
    - secretKey: static-secret
      remoteRef:
        key: foo
    - secretKey: rotated-secret
      remoteRef:
        key: bar.current
