apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: my-secret-store
spec:
  provider:
    pulumi:
      organization: logmeup
      project: kcd-brasil
      environment: development
      accessToken:
        secretRef:
          name: my-pu-secret
          key: pu-at
