apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secrets-demo
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: my-secret-store
    kind: SecretStore
  target:
    name: secrets-demo
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        aws-access-key-id: "{{ .accessKeyId }}"
        aws-secret-access-key: "{{ .secretAccessKey }}"
        aws-session-token: "{{ .sessionToken }}"
  dataFrom:
    - extract:
        key: aws.login
